### ISSUE TITLE
Date of payment

### ISSUE THREAD

**Issue by Tarom11** [ch2877/swiss-payment#8]
Thank you for this great tool.
Is it possible to enter the payment date as well?
Unfortunately I have not found it.

Best regards from St. Gallen
Tarom

**Comment by cbaconnier** [comment]
You should be able to set the payment date on the `PaymentInformation` level

```php

$payment = new PaymentInformation(
         'payment-001',  
         'InnoMuster AG',
         new BIC('ZKBKCHZZ80A'),
         new IBAN('CH6600700110000204481')
);

$payment->setExecutionDate(new \DateTime());

```

**Comment by Tarom11** [comment]
Thank you very much.
Do you know which date format to use here?

**Comment by cbaconnier** [comment]
It uses a `DateTime` class, you can set the date with the following format
```php
$payment->setExecutionDate(new \DateTime('2022-12-31'));
```
You can also use other/custom format. Refer to the DateTime documentation: https://www.php.net/manual/en/class.datetime.php

--- 
The library will format the date for the XML with the following 
```php
$this->executionDate->format('Y-m-d')
```
[PaymentInformation.php#L244](https://github.com/ch2877/swiss-payment/blob/v2.0.0/src/Z38/SwissPayment/PaymentInformation/PaymentInformation.php#L244)

If you don't provide an execution date, the library will use the date of today:  [PaymentInformation.php#L87](https://github.com/ch2877/swiss-payment/blob/v2.0.0/src/Z38/SwissPayment/PaymentInformation/PaymentInformation.php#L87)

**Comment by Tarom11** [comment]
Thank you very much.
Will test it right away.
